DmsReportWebApp/Models/ErrorViewModel.cs
using System;

namespace DmsReportWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DmsReportWebApp/Models/HelpContentItem.cs
namespace DmsReportWebApp.Models
{
    public class HelpContentItem
    {
        public string ImageUrl { get; set; }
        public string ImageCaption { get; set; }
    }
}

DmsReportWebApp/Controllers/EmployeeWorkingTimeReportController.cs
using System;
using DmsReportWebApp.Dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace DmsReportWebApp.Controllers
{
    public class EmployeeWorkingTimeQuery
    {
        public string CustomerID { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string StaffID { get; set; }
        public int Page { get; set; }
        public int PageSize { get; set; }
    }
    
    public class EmployeeWorkingTimeReportController : Controller
    {
        private IOptions<AppConfigDto> _appConfig { get; }

        public EmployeeWorkingTimeReportController(IOptions<AppConfigDto> appConfig)
        {
            _appConfig = appConfig;
        }

        // GET
        public IActionResult Index([ModelBinder] EmployeeWorkingTimeQuery query)
        {
            PrepareReport(query);
            return View("ReportV2");
        }
        
        public IActionResult TimeReportStaffAndSup([ModelBinder] EmployeeWorkingTimeQuery query)
        {
            PrepareReport(query);
            return View("TimeReportStaffAndSup");
        }

        public IActionResult ReportV2([ModelBinder] EmployeeWorkingTimeQuery query)
        {
            PrepareReport(query);
            return View("ReportV2");
        }

        private void PrepareReport(EmployeeWorkingTimeQuery query)
        {
            var reportApiBaseUrl = _appConfig.Value.ReportApiBaseUrl.TrimEnd(new[] {'/'});
            var reportPath = string.IsNullOrEmpty(_appConfig.Value.EmployeeTimeReportApiPath) ? "/api/test/getTimeKeepingByDate" 
                : _appConfig.Value.EmployeeTimeReportApiPath;
            
            ViewData["ReportApiUrl"] = $"{reportApiBaseUrl}{reportPath}";
            ViewData["authToken"] = _appConfig.Value.AuthToken;
            ViewData["dateFrom"] = string.IsNullOrEmpty(query.StartDate)
                ? GetDefaultStartDate(DateTime.Now)
                : query.StartDate;
            ViewData["dateTo"] = string.IsNullOrEmpty(query.EndDate) ? GetDefaultEndDate(DateTime.Now) : query.EndDate;
            ViewData["customerId"] = string.IsNullOrEmpty(query.CustomerID) ? "1" : query.CustomerID;
            ViewData["staffId"] = string.IsNullOrEmpty(query.StaffID) ? "192" : query.StaffID;
            ViewData["page"] = query.Page > 0 ? query.Page : 1;
            ViewData["pageSize"] = query.PageSize > 0 ? query.PageSize : 20;
            ViewData["appVersion"] = _appConfig.Value.AppVersion;
        }

        string GetDefaultStartDate(DateTime d) => $"{d.Year}-{d.Month}-01";
        string GetDefaultEndDate(DateTime d) => DateTime.Today.ToString("yyyy-MM-dd"); //$"{d.Year}-{d.Month}-{DateTime.DaysInMonth(d.Year, d.Month)}";

        [Route("AdaptiveRendering")]
        public IActionResult TestGridAdaptiveRendering()
        {
            return View("AdaptiveRendering");
        }
        
        [Route("ReportFrame")]
        public IActionResult ReportFrame()
        {
            return View("ReportFrame");
        }
    }
}

DmsReportWebApp/Controllers/HelpController.cs
using System.Collections.Generic;
using DmsReportWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DmsReportWebApp.Controllers
{
    public class HelpIndexQuery
    {
        public string P1 { get; set; }
        public string P2 { get; set; }
    }
    
    public class HelpController : Controller
    {
        public IActionResult Index([ModelBinder] HelpIndexQuery query)
        {
            var model = GetHelpContent(query);

            return View("Index", model);
        }

        IList<HelpContentItem> GetHelpContent(HelpIndexQuery query)
        {
            if (query == null || string.IsNullOrEmpty(query.P1) || string.IsNullOrEmpty(query.P2) ||
                "test".Equals(query.P1))
            {
                return GenerateDefaultHelpContent();
            }

            return QueryHelpConent(query);
        }

        private IList<HelpContentItem> GenerateDefaultHelpContent()
        {
            return new List<HelpContentItem>
            {
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/wedding.jpg",
                    ImageCaption = "wedding"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/underwater.jpg",
                    ImageCaption = "underwater"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/rocks.jpg",
                    ImageCaption = "rocks"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/wedding.jpg",
                    ImageCaption = "wedding"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/mountainskies.jpg",
                    ImageCaption = "mountainskies"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/wedding.jpg",
                    ImageCaption = "wedding"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/underwater.jpg",
                    ImageCaption = "underwater"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/rocks.jpg",
                    ImageCaption = "rocks"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/wedding.jpg",
                    ImageCaption = "wedding"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/mountainskies.jpg",
                    ImageCaption = "mountainskies"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/wedding.jpg",
                    ImageCaption = "wedding"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/underwater.jpg",
                    ImageCaption = "underwater"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/rocks.jpg",
                    ImageCaption = "rocks"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/wedding.jpg",
                    ImageCaption = "wedding"
                },
                new HelpContentItem
                {
                    ImageUrl = "https://www.w3schools.com/w3images/mountainskies.jpg",
                    ImageCaption = "mountainskies"
                },
            };
        }

        private IList<HelpContentItem> QueryHelpConent(HelpIndexQuery query)
        {
            throw new System.NotImplementedException("Query content from db");
        }
    }
}

DmsReportWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DmsReportWebApp.Models;

namespace DmsReportWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DmsReportWebApp/Views/EmployeeWorkingTimeReport/AdaptiveRendering.cshtml
@{
    ViewData["Title"] = "Adaptive Rendering";
}

<div id="grid-wrap" style="display: none;">
    <div id="grid"></div>
</div>

@section Scripts {
    <script src="~/lib/kendo/js/kendo.all.min.js"></script>
    <script>
            $(document).ready(function () {
                var isMobile = Boolean(kendo.support.mobileOS);
                var crudServiceBaseUrl = "https://demos.telerik.com/kendo-ui/service",
                    dataSource = new kendo.data.DataSource({
                        transport: {
                            read: {
                                url: crudServiceBaseUrl + "/Products",
                                dataType: "jsonp"
                            },
                            update: {
                                url: crudServiceBaseUrl + "/Products/Update",
                                dataType: "jsonp"
                            },
                            destroy: {
                                url: crudServiceBaseUrl + "/Products/Destroy",
                                dataType: "jsonp"
                            },
                            create: {
                                url: crudServiceBaseUrl + "/Products/Create",
                                dataType: "jsonp"
                            },
                            parameterMap: function (options, operation) {
                                if (operation !== "read" && options.models) {
                                    return { models: kendo.stringify(options.models) };
                                }
                            }
                        },
                        batch: true,
                        pageSize: 20,
                        schema: {
                            model: {
                                id: "ProductID",
                                fields: {
                                    ProductID: { editable: false, nullable: true },
                                    ProductName: { validation: { required: true } },
                                    UnitPrice: { type: "number", validation: { required: true, min: 1 } },
                                    Discontinued: { type: "boolean" },
                                    UnitsInStock: { type: "number", validation: { min: 0, required: true } }
                                }
                            }
                        }
                    });
    
                $("#grid").kendoGrid({
                    dataSource: dataSource,
                    toolbar: ["create"],
                    height: 450,
                    mobile: true,
                    sortable: true,
                    pageable: true,
                    resizable: true,
                    filterable: true,
                    columnMenu: true,
                    columns: [
                        { field: "ProductName", title: "Product Name", filterable: { multi: true, search: true }, width: "120px" },
                        { field: "UnitPrice", title: "Unit Price", format: "{0:c}", width: "120px" },
                        { field: "UnitsInStock", title: "Units In Stock", width: "120px" },
                        { field: "Discontinued", width: "120px" },
                        { command: ["edit", "destroy"], title: "&nbsp;", width: "250px" }],
                    editable: "popup"
                });                   
    
                if (isMobile) {
                    $("#grid-wrap").show();
                    $("#grid").data("kendoGrid").resize();
                }
            });
        </script>
}

DmsReportWebApp/Views/EmployeeWorkingTimeReport/Index.cshtml
@{
    ViewData["Title"] = "Báo Cáo Chấm Công";
}

<input type="hidden" id="hidReportApiUrl" value="@ViewData["ReportApiUrl"]"/>
<input type="hidden" id="hidAuthToken" value="@ViewData["authToken"]"/>
<input type="hidden" id="hidDateFrom" value="@ViewData["dateFrom"]"/>
<input type="hidden" id="hidDateTo" value="@ViewData["dateTo"]"/>
<input type="hidden" id="hidPageSize" value="@ViewData["pageSize"]"/>
<input type="hidden" id="hidPage" value="@ViewData["page"]"/>
<input type="hidden" id="hidStaffId" value="@ViewData["staffId"]"/>
<input type="hidden" id="hidCustomerId" value="@ViewData["customerId"]"/>
<div class="row app-divider-row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <input id="dpFrom" class="app-form-control" placeholder="Date from" value="@ViewData["dateFrom"]"/>
        <input id="dpTo" class="app-form-control" placeholder="Date to" value="@ViewData["dateTo"]"/>
        <button id="btnViewReport" type="button" class="btn btn-sm btn-primary">Xem</button>
    </div>
</div>
<div class="row app-divider-row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <span class="mr-sm-2 app-label">Ngày LV</span>
        <span class="mr-sm-2"><strong id="headerWorkingDay"></strong></span>
        <span class="col-1">&nbsp;</span>
        <span class="mr-sm-2 app-label">Định mức TT:</span>
        <span>&nbsp;</span>
        <span class="mr-sm-2 app-label">SS</span>
        <span class="mr-sm-2"><strong id="ssMoneyLevel"></strong></span>
        <span class="col-1">&nbsp;</span>
        <span class="mr-sm-2 app-label">SM</span>
        <span class="mr-sm-2"><strong id="smMoneyLevel"></strong></span>
    </div>
</div>
<div id="grid" class="app-grid"></div>

@section Scripts {
    <script src="~/lib/kendo/js/kendo.all.min.js"></script>
    @* <script src="~/lib/kendo/js/kendo.core.min.js"></script> *@
    @* <script src="~/lib/kendo/js/kendo.data.min.js"></script> *@
    @* <script src="~/lib/kendo/js/kendo.grid.min.js"></script> *@
    @* <script src="~/lib/kendo/js/kendo.datepicker.min.js"></script> *@
    @* <script src="~/lib/kendo/js/kendo.web.min.js"></script> *@
    @* <script src="~/js/mock-report-data.js"></script> *@
    <script src="~/js/employee-time-report.js" asp-append-version="true"></script>
}

DmsReportWebApp/Views/EmployeeWorkingTimeReport/ReportFrame.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Report</title>
</head>
<body style="margin: 0">
<iframe src="https://rptpltc.2soft.vn/EmployeeWorkingTimeReport?customerId=1&staffId=1" 
        style="position:fixed; top:0; left:0; bottom:0; right:0; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;">
    Your browser doesn't support iframes
</iframe>
</body>
</html>

DmsReportWebApp/Views/EmployeeWorkingTimeReport/ReportV2.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Báo Cáo Chấm Công</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.common.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.office365.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.office365.mobile.min.css" />
        <link rel="stylesheet" href="~/css/employee_time_working_report_v2.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.common.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.office365.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.office365.mobile.min.css" />
        <link rel="stylesheet" href="~/css/employee_time_working_report_v2.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        <input type="hidden" id="hidReportApiUrl" value="@ViewData["ReportApiUrl"]"/>
        <input type="hidden" id="hidAuthToken" value="@ViewData["authToken"]"/>
        <input type="hidden" id="hidDateFrom" value="@ViewData["dateFrom"]"/>
        <input type="hidden" id="hidDateTo" value="@ViewData["dateTo"]"/>
        <input type="hidden" id="hidPageSize" value="@ViewData["pageSize"]"/>
        <input type="hidden" id="hidPage" value="@ViewData["page"]"/>
        <input type="hidden" id="hidStaffId" value="@ViewData["staffId"]"/>
        <input type="hidden" id="hidCustomerId" value="@ViewData["customerId"]"/>
        <div class="row app-divider-row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <input id="dpFrom" class="app-form-control" placeholder="Date from" value="@ViewData["dateFrom"]"/>
                <input id="dpTo" class="app-form-control" placeholder="Date to" value="@ViewData["dateTo"]"/>
                <button id="btnViewReport" type="button" class="btn btn-sm btn-primary">Xem</button>
            </div>
        </div>
        <div class="row app-divider-row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <span class="mr-sm-2 app-label">Ngày LV</span>
                <span class="mr-sm-2"><strong id="headerWorkingDay"></strong></span>
                <span class="col-1">&nbsp;</span>
                <span class="mr-sm-2 app-label">Định mức TT:</span>
                <span>&nbsp;</span>
                <span class="mr-sm-2 app-label">SS</span>
                <span class="mr-sm-2"><strong id="ssMoneyLevel"></strong></span>
                <span class="col-1">&nbsp;</span>
                <span class="mr-sm-2 app-label">SM</span>
                <span class="mr-sm-2"><strong id="smMoneyLevel"></strong></span>
            </div>
        </div>
        <div id="grid" class="app-grid"></div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
    </environment>
    <script src="~/lib/kendo/js/kendo.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/employee-time-report-v2.js" asp-append-version="true"></script>
</body>
</html>

DmsReportWebApp/Views/EmployeeWorkingTimeReport/TimeReportStaffAndSup.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Báo Cáo Chấm Công</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.common.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.default.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.default.mobile.min.css" />
        @* <link rel="stylesheet" href="~/lib/kendo/styles/kendo.office365.min.css" /> *@
        @* <link rel="stylesheet" href="~/lib/kendo/styles/kendo.office365.mobile.min.css" /> *@
        <link rel="stylesheet" href="~/css/employee_time_working_report_v2.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.common.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.default.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/styles/kendo.default.mobile.min.css" />
        <link rel="stylesheet" href="~/css/employee_time_working_report_v2.css" asp-append-version="true" />
    </environment>
</head>
<body>
<div class="container-fluid body-content">
    <input type="hidden" id="hidReportApiUrl" value="@ViewData["ReportApiUrl"]"/>
    <input type="hidden" id="hidAuthToken" value="@ViewData["authToken"]"/>
    <input type="hidden" id="hidDateFrom" value="@ViewData["dateFrom"]"/>
    <input type="hidden" id="hidDateTo" value="@ViewData["dateTo"]"/>
    <input type="hidden" id="hidPageSize" value="@ViewData["pageSize"]"/>
    <input type="hidden" id="hidPage" value="@ViewData["page"]"/>
    <input type="hidden" id="hidStaffId" value="@ViewData["staffId"]"/>
    <input type="hidden" id="hidCustomerId" value="@ViewData["customerId"]"/>
    <div class="row app-divider-row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <input id="dpFrom" class="app-form-control" placeholder="Date from" value="@ViewData["dateFrom"]"/>
            <input id="dpTo" class="app-form-control" placeholder="Date to" value="@ViewData["dateTo"]"/>
            <button id="btnViewReport" type="button" class="btn btn-sm btn-primary">Xem</button>
        </div>
    </div>
    <div class="row app-divider-row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <span class="mr-sm-2 app-label">Ngày LV</span>
            <span class="mr-sm-2"><strong id="headerWorkingDay"></strong></span>
            <span class="col-1">&nbsp;</span>
            <span class="mr-sm-2 app-label">Định mức TT:</span>
            <span>&nbsp;</span>
            <span class="mr-sm-2 app-label">SS</span>
            <span class="mr-sm-2"><strong id="ssMoneyLevel"></strong></span>
            <span class="col-1">&nbsp;</span>
            <span class="mr-sm-2 app-label">SM</span>
            <span class="mr-sm-2"><strong id="smMoneyLevel"></strong></span>
        </div>
    </div>
    <div id="grid" class="app-grid"></div>
</div>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
</environment>
<script src="~/lib/kendo/js/kendo.all.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/employee-time-report-staff-sup.js" asp-append-version="true"></script>
</body>
</html>

DmsReportWebApp/Views/Help/Index.cshtml
@model IList<HelpContentItem>

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Help</title>
  <link rel="stylesheet" href="~/css/site_help.css" asp-append-version="true" />
</head>
<body>
<!-- Photo Grid -->
<div class="row">
  @{
    foreach (var helpContentItem in Model)
    {
      <div class="column">
        <img src="@helpContentItem.ImageUrl" class="image-center">
        <figcaption>@helpContentItem.ImageCaption</figcaption>
      </div>
    }
  }
</div>

</body>
</html>

DmsReportWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DmsReportWebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DmsReportWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <ul>
        <li>
            <a class="nav-link" asp-area=""
               asp-controller="EmployeeWorkingTimeReport"
               asp-action="Index"
               asp-route-customerId="1"
               asp-route-staffId="192">
                Báo Cáo Chấm Công
            </a>
        </li>
        <li>
            <a class="nav-link" asp-area=""
               asp-controller="EmployeeWorkingTimeReport"
               asp-action="ReportV2"
               asp-route-customerId="1"
               asp-route-staffId="192">
                Báo Cáo Chấm Công V2
            </a>
        </li>
        <li>
            <a class="nav-link" asp-area=""
               asp-controller="EmployeeWorkingTimeReport"
               asp-action="TimeReportStaffAndSup"
               asp-route-customerId="1"
               asp-route-staffId="192">
                Báo Cáo Chấm Công GSBH
            </a>
        </li>
        <li>
            <a class="nav-link" asp-area=""
               asp-controller="EmployeeWorkingTimeReport"
               asp-action="TimeReportStaffAndSup"
               asp-route-customerId="1"
               asp-route-staffId="193">
                Báo Cáo Chấm Công NVBH
            </a>
        </li>
        <li>
            <a class="nav-link" asp-area=""
               asp-controller="Help"
               asp-action="Index">
                Help
            </a>
        </li>
    </ul>
</div>